version: '3'
services:
  catalog-module:
    image: siddhanthhn/catalog-service
    ports: 
     - "8000:80"
  redis:
    image: redis:alpine
  Review-Module:
    image: siddhanthhn/review-service
    ports:
     - "8050:90"
  Order-Module:
    image: siddhanthhn/order-service
    ports:
     - "8100:100"
